{% set versions = {
    "HEAD": "HEAD"
} %}

{% set version = environ.get('COMMIT_VERSION', None) %}
{% set version = version or versions.keys()|first %}
{% set version = version|string %}

package:
  name: {{ environ.get('ANACONDA_PACKAGE', "rkafka")|string|lower }}
  version: {{ environ.get('ANACONDA_VERSION', version)|replace("-", ".") }}

source:
  git_url: "https://git.ligo.org/kagra/libraries-addons/root/kafka"
  git_rev: {{ version }}

requirements:
  build:
    - {{ compiler('cxx') }} # [linux]
    - {{ compiler('c') }}   # [linux]
    - {{ stdlib('c') }}

    - clang
    - cmake
    - make

    - cuda-nvcc

  host:
    - root-plus
    - cparser
    - librdkafka

  run:
    - root-plus
    - cparser

about:
  home: "https://git.ligo.org/kagra/libraries-addons/root/kafka"
  license: "GPL-3.0"
  summary: "KAFKA Client using ROOT"
  description: |
    RKafka is a ROOT addons allowing to connect KAFKA server

extra:
  recipe-maintainers:
    - meiyasan
